In [1]:
    import numpy as np
    
    import pandas as pd
    
    import matplotlib.pyplot as plt
    %matplotlib inline
    
    from math import *
    
    from random import uniform

In [16]:
Tab_Pok=pd.read_csv('Système Pokémon.csv',sep=';')
print(Tab_Pok)

      Code  Numero                           Nom   PV  Att  Def   AS   DS  \
0        1       1                    Bulbizarre   45   49   49   65   65   
1        2       2                    Herbizarre   60   62   63   80   80   
2        3       3                    Florizarre   80   82   83  100  100   
3        4       3               Mega-Florizarre   80  100  123  122  120   
4        5       4                     Salameche   39   52   43   60   50   
...    ...     ...                           ...  ...  ...  ...  ...  ...   
1012  1013     889     Zamazenta (Heros Aguerri)   92  130  115   80  115   
1013  1014     889  Zamazenta (Bouclier Supreme)   92  130  145   80  145   
1014  1015     890                    Ethernatos  140   85   95  145   95   
1015  1016     890        Ethernatos (Infinimax)  255  115  250  125  250   
1016  1017     891                         Reshi   60   70   70  100   50   

      Vit  Total  
0      45    318  
1      60    405  
2      80    525  

In [3]:
sta=np.array([1,1,1,1,1,1])
IV=np.random.randint(0, 32, 6)
b=5

In [4]:
import numpy as np    
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline   
from math import *

def generator(nom,niveau): #Générateur d'un Pokémon de niveau donné, sans EV et avec tirage aléatoire de ses IV et nature
    Nat=pd.read_csv('Natures.csv',sep='\t')
    nature=np.random.randint(0, 25, 1)
    i=nature[0]
    Tab_Pok=pd.read_csv('Système Pokémon.csv',sep=';')
    sta=np.array([1,1,1,1,1,1])
    IV=np.random.randint(0, 32, 6)
    j=0
    sta[0]=(2*Tab_Pok['PV'][j]+IV[0])*niveau/100+niveau+10
    sta[1]=((2*Tab_Pok['Att'][j]+IV[1])*niveau/100+5)*Nat['A'][i]
    sta[2]=((2*Tab_Pok['Def'][j]+IV[2])*niveau/100+5)*Nat['D'][i]
    sta[3]=((2*Tab_Pok['AS'][j]+IV[3])*niveau/100+5)*Nat['AS'][i]
    sta[4]=((2*Tab_Pok['DS'][j]+IV[4])*niveau/100+5)*Nat['DS'][i]
    sta[5]=((2*Tab_Pok['Vit'][j]+IV[5])*niveau/100+5)*Nat['Vit'][i]
    txt='Bulbizarre'
    while txt!=nom :
        j=j+1
        txt=Tab_Pok['Nom'][j]
        sta[0]=(2*Tab_Pok['PV'][j]+IV[0])*niveau/100+niveau+10
        sta[1]=((2*Tab_Pok['Att'][j]+IV[1])*niveau/100+5)*Nat['A'][i]
        sta[2]=((2*Tab_Pok['Def'][j]+IV[2])*niveau/100+5)*Nat['D'][i]
        sta[3]=((2*Tab_Pok['AS'][j]+IV[3])*niveau/100+5)*Nat['AS'][i]
        sta[4]=((2*Tab_Pok['DS'][j]+IV[4])*niveau/100+5)*Nat['DS'][i]
        sta[5]=((2*Tab_Pok['Vit'][j]+IV[5])*niveau/100+5)*Nat['Vit'][i]
    print(j)
    print('Les statistiques de ',nom,'sont :',sta)
    print('Ses IV sont :',IV,' et sa nature est',Nat['Nature'][i])

generator('Bulbizarre',100)


0
Les statistiques de  Bulbizarre sont : [229 134 105 126 135 138]
Ses IV sont : [29 31  2  6  0 31]  et sa nature est Jovial


In [5]:
generator('Pikachu',25)

33
Les statistiques de  Pikachu sont : [58 35 25 33 33 53]
Ses IV sont : [24 26  3 14  1 13]  et sa nature est Calme


In [6]:
sta

array([1, 1, 1, 1, 1, 1])

In [7]:
generator('Nosferapti',15)

55
Les statistiques de  Nosferapti sont : [37 22 16 17 18 24]
Ses IV sont : [ 6 27 21 15  8 17]  et sa nature est Doux


In [8]:
sta

array([1, 1, 1, 1, 1, 1])

In [9]:
txt=Tab_Pok['Nom'][915]
txt

'Katagami'

In [10]:
c=100

In [11]:
Tab_Pok['PV'][i]

NameError: name 'i' is not defined

In [12]:
nature=np.random.randint(0, 25, 1)
nature

array([7])

In [13]:
i=nature[0]
i

7

In [14]:
Nat=pd.read_csv('Natures.csv',sep='\t')
Nat

Nature    A    D   AS   DS  Vit GoûtPréféré GoûtDétesté
0    Assuré  0.9  1.1  1.0  1.0  1.0       Acide       Épicé
1   Bizarre  1.0  1.0  1.0  1.0  1.0       Aucun       Aucun
2     Brave  1.1  1.0  1.0  1.0  0.9       Épicé       Sucré
3     Calme  0.9  1.0  1.0  1.1  1.0        Amer       Épicé
4   Discret  1.0  1.0  1.1  1.0  0.9         Sec       Sucré
5    Docile  1.0  1.0  1.0  1.0  1.0       Aucun       Aucun
6      Doux  1.0  0.9  1.1  1.0  1.0         Sec       Acide
7    Foufou  1.0  1.0  1.1  0.9  1.0         Sec        Amer
8    Gentil  1.0  0.9  1.0  1.1  1.0        Amer       Acide
9     Hardi  1.0  1.0  1.0  1.0  1.0       Aucun       Aucun
10   Jovial  1.0  1.0  0.9  1.0  1.1       Sucré         Sec
11    Lâche  1.0  1.1  1.0  0.9  1.0       Acide        Amer
12    Malin  1.0  1.1  0.9  1.0  1.0       Acide         Sec
13  Malpoli  1.0  1.0  1.0  1.1  0.9        Amer       Sucré
14  Mauvais  1.1  1.0  1.0  0.9  1.0       Épicé        Amer
15  Modeste  0.9  1.0  1.1  1.0  1.0         Sec       Épicé
16     Naïf  1.0  1.0  1.0  0.9  1.1       Sucré        Amer
17   Pressé  1.0  0.9  1.0  1.0  1.1       Sucré       Acide
18  Prudent  1.0  1.0  0.9  1.1  1.0        Amer         Sec
19  Pudique  1.0  1.0  1.0  1.0  1.0       Aucun       Aucun
20    Relax  1.0  1.1  1.0  1.0  0.9       Acide       Sucré
21   Rigide  1.1  1.0  0.9  1.0  1.0       Épicé         Sec
22  Sérieux  1.0  1.0  1.0  1.0  1.0       Aucun       Aucun
23     Solo  1.1  0.9  1.0  1.0  1.0       Épicé       Acide
24   Timide  0.9  1.0  1.0  1.0  1.1       Sucré       Épicé

In [15]:
def stat(nom,niveau,IV,EV,nature):#Calcul des statistiques du Pokémon "nom". IV et EV sont des vecteurs à 6 composantes
    Nat=pd.read_csv('Natures.csv',sep='\t')
    txtn='Assuré'
    i=0
    Tab_Pok=pd.read_csv('Système Pokémon.csv',sep=';')
    sta=np.array([1,1,1,1,1,1])
    j=0
    txt='Bulbizarre'
    while txtn!=nature:
        i=i+1
        txtn=Nat['Nature'][i]
    while txt!=nom:
        j=j+1
        txt=Tab_Pok['Nom'][j]
        sta[0]=(2*Tab_Pok['PV'][j]+IV[0]+EV[0]/4)*niveau/100+niveau+10
        sta[1]=((2*Tab_Pok['Att'][j]+IV[1]+EV[1]/4)*niveau/100+5)*Nat['A'][i]
        sta[2]=((2*Tab_Pok['Def'][j]+IV[2]+EV[2]/4)*niveau/100+5)*Nat['D'][i]
        sta[3]=((2*Tab_Pok['AS'][j]+IV[3]+EV[3]/4)*niveau/100+5)*Nat['AS'][i]
        sta[4]=((2*Tab_Pok['DS'][j]+IV[4]+EV[4]/4)*niveau/100+5)*Nat['DS'][i]
        sta[5]=((2*Tab_Pok['Vit'][j]+IV[5]+EV[5]/4)*niveau/100+5)*Nat['Vit'][i]
    print(i,j)
    print('Les statistiques de ',nom,'sont :',sta)
    
stat('Florizarre',6,[6,6,27,7,0,6],[0,0,0,0,0,0],'Bizarre')

1 2
Les statistiques de  Florizarre sont : [25 15 16 17 17 14]


In [19]:
stat('Reshi',5,[27,26,25,30,23,25],[0,0,0,0,0,0],'Bizarre')

1 1016
Les statistiques de  Reshi sont : [22 13 13 16 11 11]


In [10]:
def Degats(Attaquant,Defenseur,Type,CM,Puissance,moda,modd):#Type = Phy ou Spe, CM est le coeff multiplicateur, dépendant de stab, 
    # Faiblesse/résistance, CC, Climat, etc.
    PV=0 # Initialisation des PV perdus
    Att=0 # Initialisation de la valeur d'attaque
    Def=0 # Initialisation de la valeur de défense
    alea=uniform(0.85,1) # Nombre aléatoire utilisé dans le calcul de dégâts
    Données=pd.read_csv('Dégâts.csv',sep='\t') # Fichier des stats et niveau des concernés
    txta='Test' # Initialisation du nom de l'attaquant dans le fichier des concernés
    i=0
    txtd='Test'  # Initialisation du nom du défenseur dans le fichier des concernés
    j=0
    while txta!=Attaquant: #Boucle servant à sélectionner la ligne de données de l'attaquant
        i=i+1
        txta=Données['Nom'][i]
    while txtd!=Defenseur: #Boucle servant à sélectionner la ligne de données du défenseur
        j=j+1
        txtd=Données['Nom'][j]
    if Type == 'Phy': #Si l'attaque est de catégorie physique
        Att=moda*Données['A'][i]
        Def=modd*Données['D'][j]
    else: #Si l'attaque est de catégorie spéciale
        Att=moda*Données['AS'][i]
        Def=modd*Données['DS'][j]
    
    PV=int(CM*alea*(2+(Données['Niveau'][i]*0.4+2)*Att*Puissance/Def/50))
    print(i,j)
    print(Defenseur,' perd ',PV,' points de vie !')

In [17]:
Données=pd.read_csv('Dégâts.csv',sep='\t')
Données.loc[1,'AS']

40

In [16]:
Degats('Ruby','Galekid','Spe',1,40,1,1)

1 2
Galekid  perd  27  points de vie !


In [17]:
generator('Humain 3',100)

KeyError: 1016

In [14]:
h=1,1

In [15]:
h

(1, 1)

In [43]:
uniform(0.85,1)

0.9994591796471883

In [23]:
def exp(basexp,niveau,bonus): #Fonction calculant les points d'expérience obtenus en mettant KO un adversaire
    a=int(bonus*basexp*niveau/7)
    print('Vous gagnez ',a,' points d\'expérience !')

In [24]:
exp(6,5,1)

Vous gagnez  4  points d'expérience !


In [25]:
def calexp(niveau,courbe):
    if courbe=='rapide':
        exp=0.8*niveau*niveau*niveau
    elif courbe=='moyenne':
        exp=niveau*niveau*niveau
    elif courbe=='parabolique':
        exp=1.2*niveau*niveau*niveau-15*niveau*niveau+100*niveau-140
    elif courbe=='lente':
        exp=1.25*niveau*niveau*niveau
    elif courbe=='erratique':
        if 0<niveau<51:
            exp=niveau*niveau*niveau*(100-niveau)/50
        elif 50<niveau<69:
            exp=niveau*niveau*niveau*(150-niveau)/100
        elif 68<niveau<99:
            if niveau%3==0:
                exp=niveau*niveau*niveau*(1.274-niveau/150)
            elif niveau%3==1:
                exp=niveau*niveau*niveau*(1.274-niveau/150-0.008)
            elif niveau%3==2:
                exp=niveau*niveau*niveau*(1.274-niveau/150-0.014)
        elif 98<niveau<101:
            exp=niveau*niveau*niveau*(160-niveau)/100
    elif courbe=='fluctuante':
        if 0<niveau<16:
            exp=niveau*niveau*niveau/50*(24+(niveau+1)/3)
        elif 15<niveau<36:
            exp=niveau*niveau*niveau/50*(14+niveau)
        elif 35<niveau<101:
            exp=niveau*niveau*niveau/50*(32+niveau/2)
    print('L\'expérience pour atteindre le niveau ',niveau,' est de ',exp,' points d\'expérience')

In [9]:
calexp(85,'rapide')
calexp(85,'moyenne')
calexp(85,'parabolique')
calexp(85,'lente')
calexp(85,'erratique')
calexp(85,'fluctuante')

L'expérience pour atteindre le niveau  85  est de  491300.0  points d'expérience
L'expérience pour atteindre le niveau  85  est de  614125  points d'expérience
L'expérience pour atteindre le niveau  85  est de  636935.0  points d'expérience
L'expérience pour atteindre le niveau  85  est de  767656.25  points d'expérience
L'expérience pour atteindre le niveau  85  est de  429478.0833333334  points d'expérience
L'expérience pour atteindre le niveau  85  est de  915046.25  points d'expérience


In [26]:
def prob(pre,esq,att):
    p=pre*att/esq
    print('La probabilité de toucher est de ',p,'%')

In [13]:
prob(1,1,90)

La probabilité de toucher est de  90.0 %


In [12]:
prob(133,60,90)

La probabilité de toucher est de  199.5 %


In [13]:
prob(60,133,90)

La probabilité de toucher est de  40.6015037593985 %
